// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrqqom--TNszdU0s2t85_HaK7HB8fOpeM',
    appId: '1:497223318411:web:32936cd40d1d4a048dcd8e',
    messagingSenderId: '497223318411',
    projectId: 'payment-916ea',
    authDomain: 'payment-916ea.firebaseapp.com',
    storageBucket: 'payment-916ea.appspot.com',
    measurementId: 'G-FSFCZ66XFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8IisDvv5gRtOZskTm0QVi6wDoFlw9j2M',
    appId: '1:497223318411:android:5a5fc94a323b431a8dcd8e',
    messagingSenderId: '497223318411',
    projectId: 'payment-916ea',
    storageBucket: 'payment-916ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMc_3JvTPhZ4EVUAAC0xWRYm7Em1iUs5k',
    appId: '1:497223318411:ios:f98541e8a7fd7c4d8dcd8e',
    messagingSenderId: '497223318411',
    projectId: 'payment-916ea',
    storageBucket: 'payment-916ea.appspot.com',
    iosBundleId: 'com.example.paymentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMc_3JvTPhZ4EVUAAC0xWRYm7Em1iUs5k',
    appId: '1:497223318411:ios:f98541e8a7fd7c4d8dcd8e',
    messagingSenderId: '497223318411',
    projectId: 'payment-916ea',
    storageBucket: 'payment-916ea.appspot.com',
    iosBundleId: 'com.example.paymentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrqqom--TNszdU0s2t85_HaK7HB8fOpeM',
    appId: '1:497223318411:web:a53acf90a9b89e1b8dcd8e',
    messagingSenderId: '497223318411',
    projectId: 'payment-916ea',
    authDomain: 'payment-916ea.firebaseapp.com',
    storageBucket: 'payment-916ea.appspot.com',
    measurementId: 'G-NS3S2P6YQ8',
  );
}
